name: CI (app-web)

on:
  push:
    paths:
      - 'app-web/**'
      - '.github/workflows/app-web.yml'
  workflow_dispatch:


defaults:
  run:
    working-directory: ./app-web

env:
  NODE_VERSION: 14.x

jobs:
  deploy:
    name: Deploy
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Build
      - name: Install dependencies
        run: yarn
      - name: Build project
        run: CI= yarn build

      # Deploy
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy
        run: yarn deploy

